const ROLES = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  EMPLOYEE: "EMPLOYEE",
};

const ROLE_HIERARCHY = {
  ADMIN: ["ADMIN", "MANAGER", "EMPLOYEE"],
  MANAGER: ["MANAGER", "EMPLOYEE"],
  EMPLOYEE: ["EMPLOYEE"],
};

const PERMISSIONS = {
  // Asset permissions
  ASSET_CREATE: [ROLES.ADMIN, ROLES.MANAGER],
  ASSET_READ: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  ASSET_UPDATE: [ROLES.ADMIN, ROLES.MANAGER],
  ASSET_DELETE: [ROLES.ADMIN],
  ASSET_ALLOCATE: [ROLES.ADMIN, ROLES.MANAGER],
  ASSET_DEALLOCATE: [ROLES.ADMIN, ROLES.MANAGER],
  ASSET_TRANSFER: [ROLES.ADMIN, ROLES.MANAGER],

  // Department permissions
  DEPARTMENT_CREATE: [ROLES.ADMIN],
  DEPARTMENT_READ: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  DEPARTMENT_UPDATE: [ROLES.ADMIN],
  DEPARTMENT_DELETE: [ROLES.ADMIN],

  // User permissions
  USER_CREATE: [ROLES.ADMIN],
  USER_READ: [ROLES.ADMIN, ROLES.MANAGER],
  USER_UPDATE: [ROLES.ADMIN],
  USER_DELETE: [ROLES.ADMIN],
  USER_MANAGE_SELF: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],

  // Booking permissions
  BOOKING_CREATE: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  BOOKING_APPROVE: [ROLES.ADMIN, ROLES.MANAGER],
  BOOKING_CANCEL: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],

  // Maintenance permissions
  MAINTENANCE_CREATE: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  MAINTENANCE_ASSIGN: [ROLES.ADMIN, ROLES.MANAGER],
  MAINTENANCE_UPDATE: [ROLES.ADMIN, ROLES.MANAGER],
  MAINTENANCE_DELETE: [ROLES.ADMIN],

  // Transfer permissions
  TRANSFER_REQUEST: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  TRANSFER_APPROVE: [ROLES.ADMIN, ROLES.MANAGER],
  TRANSFER_COMPLETE: [ROLES.ADMIN, ROLES.MANAGER],

  // Audit permissions
  AUDIT_CREATE: [ROLES.ADMIN],
  AUDIT_ASSIGN: [ROLES.ADMIN, ROLES.MANAGER],
  AUDIT_COMPLETE: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],

  // Report permissions
  REPORT_CREATE: [ROLES.ADMIN, ROLES.MANAGER],
  REPORT_READ: [ROLES.ADMIN, ROLES.MANAGER],
  REPORT_DELETE: [ROLES.ADMIN],

  // Notification permissions
  NOTIFICATION_READ: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],
  NOTIFICATION_DELETE: [ROLES.ADMIN, ROLES.MANAGER, ROLES.EMPLOYEE],

  // System permissions
  SYSTEM_SETTINGS: [ROLES.ADMIN],
  SYSTEM_BACKUP: [ROLES.ADMIN],
  ACTIVITY_LOG_READ: [ROLES.ADMIN],
};

function hasPermission(role, permission) {
  const allowedRoles = PERMISSIONS[permission];
  if (!allowedRoles) return false;
  return allowedRoles.includes(role);
}

function hasMinRole(userRole, requiredRole) {
  return ROLE_HIERARCHY[userRole]?.includes(requiredRole) || false;
}

module.exports = {
  ROLES,
  ROLE_HIERARCHY,
  PERMISSIONS,
  hasPermission,
  hasMinRole,
};
