const STATUSES = {
  ASSET: {
    AVAILABLE: "AVAILABLE",
    ALLOCATED: "ALLOCATED",
    UNDER_MAINTENANCE: "UNDER_MAINTENANCE",
    RETIRED: "RETIRED",
    LOST: "LOST",
    RESERVED: "RESERVED",
  },
  TRANSFER: {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    COMPLETED: "COMPLETED",
  },
  BOOKING: {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    ACTIVE: "ACTIVE",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
  },
  MAINTENANCE: {
    REQUESTED: "REQUESTED",
    SCHEDULED: "SCHEDULED",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
  },
  AUDIT: {
    DRAFT: "DRAFT",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED",
    OVERDUE: "OVERDUE",
  },
};

const STATUS_TRANSITIONS = {
  ASSET: {
    AVAILABLE: ["ALLOCATED", "RESERVED", "UNDER_MAINTENANCE", "RETIRED", "LOST"],
    ALLOCATED: ["AVAILABLE", "UNDER_MAINTENANCE", "LOST"],
    UNDER_MAINTENANCE: ["AVAILABLE", "RETIRED", "LOST"],
    RESERVED: ["ALLOCATED", "AVAILABLE", "RETIRED"],
    RETIRED: [],
    LOST: ["AVAILABLE"],
  },
  TRANSFER: {
    PENDING: ["APPROVED", "REJECTED"],
    APPROVED: ["COMPLETED", "REJECTED"],
    REJECTED: [],
    COMPLETED: [],
  },
  BOOKING: {
    PENDING: ["APPROVED", "REJECTED", "CANCELLED"],
    APPROVED: ["ACTIVE", "CANCELLED"],
    REJECTED: [],
    ACTIVE: ["COMPLETED", "CANCELLED"],
    COMPLETED: [],
    CANCELLED: [],
  },
  MAINTENANCE: {
    REQUESTED: ["SCHEDULED", "IN_PROGRESS", "CANCELLED"],
    SCHEDULED: ["IN_PROGRESS", "CANCELLED"],
    IN_PROGRESS: ["COMPLETED", "CANCELLED"],
    COMPLETED: [],
    CANCELLED: [],
  },
  AUDIT: {
    DRAFT: ["IN_PROGRESS"],
    IN_PROGRESS: ["COMPLETED", "OVERDUE"],
    COMPLETED: [],
    OVERDUE: ["IN_PROGRESS", "COMPLETED"],
  },
};

const NOTIFICATION_TYPES = {
  ASSET_ALLOCATED: "ASSET_ALLOCATED",
  ASSET_RETURNED: "ASSET_RETURNED",
  TRANSFER_REQUESTED: "TRANSFER_REQUESTED",
  TRANSFER_APPROVED: "TRANSFER_APPROVED",
  TRANSFER_REJECTED: "TRANSFER_REJECTED",
  MAINTENANCE_REQUESTED: "MAINTENANCE_REQUESTED",
  MAINTENANCE_SCHEDULED: "MAINTENANCE_SCHEDULED",
  MAINTENANCE_COMPLETED: "MAINTENANCE_COMPLETED",
  BOOKING_REQUESTED: "BOOKING_REQUESTED",
  BOOKING_APPROVED: "BOOKING_APPROVED",
  BOOKING_REJECTED: "BOOKING_REJECTED",
  AUDIT_ASSIGNED: "AUDIT_ASSIGNED",
  AUDIT_COMPLETED: "AUDIT_COMPLETED",
  GENERAL: "GENERAL",
};

const MAINTENANCE_PRIORITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

const MAINTENANCE_PRIORITY_WEIGHT = {
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
  CRITICAL: 4,
};

function canTransition(entityType, currentStatus, newStatus) {
  const allowed = STATUS_TRANSITIONS[entityType]?.[currentStatus];
  if (!allowed) return false;
  return allowed.includes(newStatus);
}

function getStatusColor(status) {
  const colors = {
    AVAILABLE: "#22c55e",
    ALLOCATED: "#3b82f6",
    UNDER_MAINTENANCE: "#f59e0b",
    RETIRED: "#6b7280",
    LOST: "#ef4444",
    RESERVED: "#8b5cf6",
    PENDING: "#f59e0b",
    APPROVED: "#22c55e",
    REJECTED: "#ef4444",
    COMPLETED: "#22c55e",
    ACTIVE: "#3b82f6",
    CANCELLED: "#6b7280",
    REQUESTED: "#f59e0b",
    SCHEDULED: "#3b82f6",
    IN_PROGRESS: "#8b5cf6",
    DRAFT: "#6b7280",
    OVERDUE: "#ef4444",
    LOW: "#22c55e",
    MEDIUM: "#f59e0b",
    HIGH: "#f97316",
    CRITICAL: "#ef4444",
  };
  return colors[status] || "#6b7280";
}

module.exports = {
  STATUSES,
  STATUS_TRANSITIONS,
  NOTIFICATION_TYPES,
  MAINTENANCE_PRIORITIES,
  MAINTENANCE_PRIORITY_WEIGHT,
  canTransition,
  getStatusColor,
};
